steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-server:$COMMIT_SHA", "."]q
images: ["gcr.io/$PROJECT_ID/my-server:$COMMIT_SHA"]

- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run",
      "deploy",
      "my-server",
      "--image",
      "gcr.io/$PROJECT_ID/my-server:$COMMIT_SHA",
      "--region",
      "us-central1",
      "--allow-unauthenticated",
    ]