    name: Github Pages Deploy
    on:
      push: 
        branches: 
          - main  # Trigger on pushes to the main branch

    jobs:
      deploy:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          pages: write
          contents: read

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install dependencies
            run: npm install

          - name: Build website  
            run: npm run build

          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: horizon
              path: build

          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
              name: horizon 
      
          - name: Deploy to GitHub Pages
            uses: actions/deploy-pages@v1
            with:
              path: build
      